### PR TITLE
Translate recurring invoice subject

### LINKED ISSUE #99: Make Send invoice subject translatable
Right now if you send an invoice (and i guess automatic sending of recurring invoices?) the subject defaults to "New invoice". It would be awesome if the default subject would translated or even better customizable in the settings.

### PR DESCRIPTION
**Pull request by mchev**
Closes #99

### CODE REVIEW

**Comment by Honigbrot** [comment]
Can we also include translations for:

- resources/scripts/admin/components/modal-components/SendPaymentModal.vue - 184
- resources/scripts/admin/components/modal-components/SendInvoiceModal.vue - line 184
- resources/scripts/admin/components/modal-components/SendEstimateModal.vue - line 169
?

I'm not really familiar with vue and translations

**Comment by mchev** [comment]
> Can we also include translations for:
> 
> - resources/scripts/admin/components/modal-components/SendPaymentModal.vue - 184
> - resources/scripts/admin/components/modal-components/SendInvoiceModal.vue - line 184
> - resources/scripts/admin/components/modal-components/SendEstimateModal.vue - line 169
> ?
> 
> I'm not really familiar with vue and translations

They already are translated with invoices.new_invoice as default subject value. If you don't see it maybe you should run 'npm run build' again.

**Comment by Honigbrot** [comment]
You are absolutely right...I was checking against the master branch not develop
Sorry for the bother!

**Review by gdarko — CHANGES_REQUESTED** [review]
Hey @mchev  - Looks like MAIL_DRIVER is used on other places. E.g. this one https://github.com/InvoiceShelf/InvoiceShelf/blob/master/app/Space/EnvironmentManager.php#L218

I would suggest we deal with that in a separate PR after reviewing if we can easily change it without implications.

Thanks.

**Comment by mchev** [comment]
> Hey @mchev - Looks like MAIL_DRIVER is used on other places. E.g. this one https://github.com/InvoiceShelf/InvoiceShelf/blob/master/app/Space/EnvironmentManager.php#L218

That's good to know for the Laravel 11 upgrade.

You are right, I shouldn't have mixed up the changes in the PR.

**Review by gdarko — APPROVED** [review]
Looks good now, Thank you.

**Pull request merged**
