### PR TITLE
Currency Separator

### LINKED ISSUE #86: Currency Separator Selection
**Is your feature request related to a problem? Please describe.**
Though I use EUR as a currency, my region uses the €100,000.00 separator style, rather than €100.000,00, which is what InvoiceShelf defaults to.

**Describe the solution you'd like**
I'd love an option (maybe in Preferences, next to the Currency selector?) to set the separator style.

**Describe alternatives you've considered**
Alternately, maybe this would be asked during initial setup, when choosing the company currency (the one that can't be changed later).

image

### PR DESCRIPTION
**Pull request by mchev**
You can now update the default separators of a currency in `/admin/settings/preferences`

Closes #86

### CODE REVIEW

**Review by gdarko — COMMENTED** [review]
Hey @mchev - 

That looks good but upon some research on this topic i realized that the current currency structure we have in the APP doesn't reflect the reality because, currencies can have different separator based on the region which is boomer. 

https://en.wikipedia.org/wiki/Decimal_separator
https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/

I propose something like this.

1. Keep currency_thousand_separator and currency_decimal_separator for each currency as defaults.
2. Make the company settings for Thousand and Decimal separator optional and add a hint that if users fills those, they override the default currency settings which is "." and ",".
3. Store Thousand and Decimal separator in the company_settings table as overrides
4. If company_settings contains thousand and decimal operator, use those. This is probably best to be implemented everywhere where the `new CurrencyResource()` instance is created.

Do you have any other suggestion?

Best,
Darko

**Comment by mchev** [comment]
I wondered about this too, but I assumed that an instance of InvoiceShelf would not be shared between several countries.
But maybe that's not true.

In that case, you effectively have to add the values to the company_settings and overwrite where necessary.

It's another job and I won't have enough time to modify all this in the next few days.

**Comment by gdarko** [comment]
No worries, @mchev - Let's keep it open and we can even delay it for the next releases.

**Comment by rihards-simanovics** [comment]
@mchev looks like you may have deleted the source branch for this PR, is this intended?

**Comment by bursaar** [comment]
Is it possible to reopen this topic? I'm in Ireland where we don't follow most other eu countries' number format, we use the same thousand and decimal separator as the US and UK. The invoices look very unusual with European formatting!

**Comment by rihards-simanovics** [comment]
> Is it possible to reopen this topic? I'm in Ireland where we don't follow most other eu countries' number format, we use the same thousand and decimal separator as the US and UK. The invoices look very unusual with European formatting!

The author of this PR deleted the branch holding the source code, hence why it's closed. If you have a bug to report or a feature to propose, please do so by opening a new issue: https://github.com/InvoiceShelf/InvoiceShelf/issues. Thanks.

**Pull request closed without merging**
