### PR TITLE
Fix translation for Recurring Invoices

### PR DESCRIPTION
**Pull request by azaricstefan**

### CODE REVIEW

**Comment by gdarko** [comment]
Hey @azaricstefan  - Is this still "Draft"?

**Comment by azaricstefan** [comment]
@gdarko yes, it is still draft, I am thinking how to resolve ENUM values ("ACTIVE" in screenshot below) of Invoices which are stored as-is in the database and then shown in the UI hardcoded.
Screenshot 2024-06-02 at 01 49 42

Any proposal for clean solution for that?

**Comment by gdarko** [comment]
> Any proposal for clean solution for that?

Hey @azaricstefan  - This is solved in the incoming PR that is related to the translations overall.

I think we can discard this PR.


Ref:

https://github.com/InvoiceShelf/InvoiceShelf/pull/69/commits/b85db8f4b7db5f355bf95fedbeaad8d749865d8a#diff-65d48583d45efb92921e3ae4d97de5a0efb6cb74ea0ed7da381b98d89362b543

#69

**Comment by azaricstefan** [comment]
Yes, you are right @gdarko, this PR #69 pretty much covers translation for recurring invoices.
Closing this draft PR.

**Pull request closed without merging**
